---
dist: xenial
sudo: false
language: ruby
cache: bundler
before_install:
  - gem install bundler -v '<2'
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - bundle exec rake
